import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Resume from "./resume";
import "bootstrap/dist/css/bootstrap.min.css";
import { Container, Row, Col, Navbar, Nav, Button } from "react-bootstrap";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Ala Arab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MyHeader />

      <main role="main">
        <Resume></Resume>
      </main>

      <footer class="text-muted">
        <div class="container">
          <p class="float-right">
            <a href="#">Back to top</a>
          </p>
          <p>2023© Ala Arab</p>
        </div>
      </footer>
    </>
  );
}

const MyHeader = () => {
  return (
    <>
      <header>
        <Navbar bg="dark" variant="dark" expand="md" className="shadow-sm">
          <Container>
            <Navbar.Brand href="#" className="d-flex align-items-center">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="20"
                height="20"
                fill="none"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                aria-hidden="true"
                className="mr-2"
                viewBox="0 0 24 24"
                focusable="false"
              >
                <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                <circle cx="12" cy="13" r="4"></circle>
              </svg>
              <strong>Ala Arab</strong>
            </Navbar.Brand>
            <Navbar.Toggle aria-controls="navbar-collapse" />
            <Navbar.Collapse id="navbar-collapse">
              <Nav className="ml-auto">
                <Container className="bg-dark py-4">
                  <Row>
                    <Col sm={8} md={7}>
                      <h4 className="text-white">About</h4>
                      <p className="text-muted">
                        Mission driven full-stack developer with a background in
                        technical support and a passion for thoughtful design
                        solutions.
                        <br />I want to make things that have an impact.
                      </p>
                    </Col>
                    <Col sm={4} md={{ span: 4, offset: 1 }}>
                      <h4 className="text-white">Contact</h4>
                      <ul className="list-unstyled">
                        <li>
                          <a
                            href="https://www.linkedin.com/in/ala-arab-a995b155/"
                            className="text-white"
                          >
                            LinkedIn
                          </a>
                        </li>
                        <li>
                          <a
                            href="mailto:alaarab@gmail.com"
                            className="text-white"
                          >
                            Email me
                          </a>
                        </li>
                      </ul>
                    </Col>
                  </Row>
                </Container>
              </Nav>
            </Navbar.Collapse>
          </Container>
        </Navbar>
      </header>
    </>
  );
};
